# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Srdjan Trajković
description: "Hey I'm Srdjan, and I'm an Actuary, Risk Manager and Data Scientist. My portfolio focuses on some projects I've recently undertaken, with a strong emphasis on business impact. I love to colaborate with interested people, crunch the data and learn new techniques and technologies. Please visit my Github & LinkedIn pages (or download my Resume) by using the links below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Belgrade, Serbia"
resume_url: /docs/Srdjan Trajkovic CV 2024 eng.pdf
avatar_image: /img/20211120_010128 portret za profil.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/sr%C4%91an-trajkovi%C4%87-57814261/" # Add your linkedln handle
github: "https://github.com/SrdjanTr"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

